export const INITIAL_CARS = [
  {
    id: "car-101",
    brand: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    pricePerDay: 180,
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 5,
    availabilityStatus: "Available",
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-fast electric luxury sedan with autopilot capabilities and executive interior."
  },
  {
    id: "car-102",
    brand: "BMW",
    model: "M4 Competition",
    year: 2023,
    pricePerDay: 150,
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 4,
    availabilityStatus: "Booked",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    description: "High-performance sports coupe featuring twin-turbo inline 6 and track dynamics."
  },
  {
    id: "car-103",
    brand: "Mercedes-Benz",
    model: "G 63 AMG",
    year: 2023,
    pricePerDay: 250,
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 5,
    availabilityStatus: "Available",
    image: "https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?auto=format&fit=crop&w=800&q=80",
    description: "Iconic luxury off-road SUV delivering powerful V8 performance and prestige status."
  },
  {
    id: "car-104",
    brand: "Audi",
    model: "RS e-tron GT",
    year: 2024,
    pricePerDay: 195,
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 5,
    availabilityStatus: "Available",
    image: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
    description: "Futuristic electric grand tourer with dual motor AWD and 800V fast charging."
  },
  {
    id: "car-105",
    brand: "Porsche",
    model: "911 Carrera S",
    year: 2023,
    pricePerDay: 220,
    fuelType: "Petrol",
    transmission: "Automatic",
    seatingCapacity: 4,
    availabilityStatus: "Maintenance",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    description: "Timeless sports car perfection with twin-turbo flat-six engine and razor-sharp handling."
  },
  {
    id: "car-106",
    brand: "Toyota",
    model: "Camry Hybrid",
    year: 2023,
    pricePerDay: 65,
    fuelType: "Hybrid",
    transmission: "Automatic",
    seatingCapacity: 5,
    availabilityStatus: "Available",
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    description: "Reliable, comfortable, and fuel-efficient hybrid midsize sedan ideal for long journeys."
  },
  {
    id: "car-107",
    brand: "Ford",
    model: "Mustang GT",
    year: 2022,
    pricePerDay: 110,
    fuelType: "Petrol",
    transmission: "Manual",
    seatingCapacity: 4,
    availabilityStatus: "Booked",
    image: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=800&q=80",
    description: "American muscle car powered by a roaring 5.0L V8 with 6-speed manual transmission."
  },
  {
    id: "car-108",
    brand: "Hyundai",
    model: "Ioniq 5",
    year: 2024,
    pricePerDay: 85,
    fuelType: "Electric",
    transmission: "Automatic",
    seatingCapacity: 5,
    availabilityStatus: "Available",
    image: "https://images.unsplash.com/photo-1662916892695-0010c732bcdd?auto=format&fit=crop&w=800&q=80",
    description: "Award-winning retro-futuristic electric crossover with lounge-like interior space."
  }
];
